// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/render": {
            "get": {
                "description": "OGP 미리보기 이미지 생성",
                "produces": [
                    "image/png"
                ],
                "summary": "OGP 미리보기 이미지 생성",
                "operationId": "render-ogp-image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "표시할 텍스트(중간에 공백이 있어야 자동 줄바꿈 처리됨)",
                        "name": "text",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "중앙 상단에 표시할 아이콘 이미지 파일의 웹 URL(없으면 표시 안하고, 이미지 조회중 오류 발생시 기본 이미지 표시)",
                        "name": "imgurl",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "배경 그라데이션 색상값(좌측 상단 시작, 6자리 16진수 색상 코드 # 없이 입력)",
                        "name": "startcolor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "배경 그라데이션 색상값(우측 하단 끝, 6자리 16진수 색상 코드 # 없이 입력)",
                        "name": "endcolor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "srvogimg",
	Description: "Open Graph Protocol Card image generater service",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
