info:
  contact: {}
  description: A Service that renders Open Graph Protocol image to share on social
    media
  title: srvogimg
  version: "1.0"
paths:
  /render:
    get:
      description: Render a OGP image with logo and text
      operationId: render-ogp-image
      parameters:
      - description: Text to display(Needs space for automatic linebreak)
        in: query
        name: text
        type: string
      - description: Web URL of the logo image to display(Show default image if error
          occured when loading)
        in: query
        name: imgurl
        type: string
      - description: Web URL of the logo image to display(Show default image if error
          occured when loading)
        in: query
        name: imgurl2
        type: string
      - description: Web URL of the logo image to display(Show default image if error
          occured when loading)
        in: query
        name: imgurl3
        type: string
      - description: 'Background gradient start (top left) color(Color code in HEX
          without #)'
        in: query
        name: startcolor
        type: string
      - description: 'Background gradient end (bottom right) color(Color code in HEX
          without #)'
        in: query
        name: endcolor
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: ""
      summary: Render a OGP image
swagger: "2.0"
