info:
  contact: {}
  description: Open Graph Protocol Card image generater service
  title: srvogimg
  version: "1.0"
paths:
  /api/render:
    get:
      description: OGP 미리보기 이미지 생성
      operationId: render-ogp-image
      parameters:
      - description: 표시할 텍스트(중간에 공백이 있어야 자동 줄바꿈 처리됨)
        in: query
        name: text
        type: string
      - description: 중앙 상단에 표시할 아이콘 이미지 파일의 웹 URL(없으면 표시 안하고, 이미지 조회중 오류 발생시 기본 이미지
          표시)
        in: query
        name: imgurl
        type: string
      - description: '배경 그라데이션 색상값(좌측 상단 시작, 6자리 16진수 색상 코드 # 없이 입력)'
        in: query
        name: startcolor
        type: string
      - description: '배경 그라데이션 색상값(우측 하단 끝, 6자리 16진수 색상 코드 # 없이 입력)'
        in: query
        name: endcolor
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: ""
      summary: OGP 미리보기 이미지 생성
swagger: "2.0"
